on: page_build
name: Purge cache on page build
jobs:
  sendPurgeCommand:
    name: Send purge command
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Send purge command
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_EMAIL: ${{ secrets.CF_EMAIL }}
        CLOUDFLARE_KEY: ${{ secrets.CF_KEY }}
        CLOUDFLARE_ZONE: ${{ secrets.CF_ZONE }}
